version: "1"
rules:
  - base: develop
    upstream: SouthGreenPlatform:master
    mergeMethod: merge
    assignees:
      - nickpalladino
      - mlm483
      - dmeidlin
      - davedrp
label: "upstream-merge"
